apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/theflockers/release-service/config/default?ref=83a3c8848f97cf2f45a7dfd350c7ec93a246d943
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/konflux-ci/release-service
    newTag: a9cb25c4896f1671c474766772f6249fdd8ec49f
namespace: release-service
