apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../base/monitor/development
  - https://github.com/theflockers/release-service/config/default?ref=d8b431059bc2411209008898a17ec660c5df3fe1
images:
  - name: quay.io/konflux-ci/release-service
    newName: quay.io/lmendes/release-service
    newTag: 2ae7e1fd-1cf1-4f48-831c-a59e9d8b726a
namespace: release-service
